apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.memsqlOperator.serviceAccountName}}
  namespace: {{ .Release.Namespace }}
{{ if .Values.serviceAccount }}
{{if .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
{{ toYaml .Values.serviceAccount.imagePullSecrets}}
{{ end }}
{{ end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: memsql-operator
  namespace: {{ .Release.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - '*'
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - memsql.com
  resources:
  - '*'
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: memsql-operator
  namespace: {{ .Release.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.memsqlOperator.serviceAccountName }}
roleRef:
  kind: Role
  name: memsql-operator
  apiGroup: rbac.authorization.k8s.io